package org.example.rms;


import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.1.1
 * 2025-03-17T17:06:51.858+08:00
 * Generated source version: 4.1.1
 *
 */
@WebService(targetNamespace = "http://microsoft.com/DRM/CertificationService", name = "CertificationWebServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface CertificationWebServiceSoap {

    @WebMethod(operationName = "Certify", action = "http://microsoft.com/DRM/CertificationService/Certify")
    @RequestWrapper(localName = "Certify", targetNamespace = "http://microsoft.com/DRM/CertificationService", className = "org.example.rms.Certify")
    @ResponseWrapper(localName = "CertifyResponse", targetNamespace = "http://microsoft.com/DRM/CertificationService", className = "org.example.rms.CertifyResponse")
    @WebResult(name = "CertifyResult", targetNamespace = "http://microsoft.com/DRM/CertificationService")
    public org.example.rms.CertifyResponse2 certify(

        @WebParam(name = "requestParams", targetNamespace = "http://microsoft.com/DRM/CertificationService")
        org.example.rms.CertifyParams requestParams
    );
}
