package org.example.wsdl;


import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.1.1
 * 2025-03-16T17:16:41.157+08:00
 * Generated source version: 4.1.1
 *
 */
@WebService(targetNamespace = "http://impl.service.example.org/", name = "HelloServiceImpl")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloServiceImpl {

    @WebMethod
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://impl.service.example.org/", className = "org.example.wsdl.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://impl.service.example.org/", className = "org.example.wsdl.SayHelloResponse")
    @WebResult(name = "resultName", targetNamespace = "")
    public java.lang.String sayHello(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
