package org.example.wsdl;

import java.net.MalformedURLException;
import java.net.URI;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by Apache CXF 4.1.1
 * 2025-03-16T17:16:41.194+08:00
 * Generated source version: 4.1.1
 *
 */
@WebServiceClient(name = "HelloServiceImplService",
                  wsdlLocation = "http://localhost:8080/ws/hello?wsdl",
                  targetNamespace = "http://impl.service.example.org/")
public class HelloServiceImplService extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("http://impl.service.example.org/", "HelloServiceImplService");
    public static final QName HelloServiceImplPort = new QName("http://impl.service.example.org/", "HelloServiceImplPort");
    static {
        URL url = null;
        try {
            url = URI.create("http://localhost:8080/ws/hello?wsdl").toURL();
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(HelloServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/ws/hello?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public HelloServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HelloServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public HelloServiceImplService(WebServiceFeature... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public HelloServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public HelloServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns HelloServiceImpl
     */
    @WebEndpoint(name = "HelloServiceImplPort")
    public HelloServiceImpl getHelloServiceImplPort() {
        return super.getPort(HelloServiceImplPort, HelloServiceImpl.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloServiceImpl
     */
    @WebEndpoint(name = "HelloServiceImplPort")
    public HelloServiceImpl getHelloServiceImplPort(WebServiceFeature... features) {
        return super.getPort(HelloServiceImplPort, HelloServiceImpl.class, features);
    }

}
